version: '3.1'

services:

  dblargedataloader:
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dblargedataloader
      POSTGRES_USER: dblargedataloader
      POSTGRES_PASSWORD: verysecret
